### ISSUE TITLE
Changing camera mode / field of view

### ISSUE THREAD

**Issue by nextnow** [keijiro/Akvj#1]
Looking for a way to set the Azure Kinect to 120 degree FOV, found this bit here:

> new DeviceConfiguration
            { ColorFormat = ImageFormat.ColorBGRA32,
              ColorResolution = ColorResolution.R1536p, // 2048 x 1536 (4:3)
              DepthMode = DepthMode.NFOV_Unbinned,      // 640x576
              SynchronizedImagesOnly = true });

Along with these settings here:

> public static int ImageWidth => 640;
    public static int ImageHeight => 576;

When I try to match what should be the WFOV_2x2Binned or WFOV_Unbinned settings with the ImageWidth and ImageHeight I either get a device error or it will start up but I get some pretty bad lines across the VFX graph effects. 

I guess my question is are there more settings that I haven't found yet, or is there another way to set this?

**Comment by keijiro** [comment]
I think you're referring to a wrong repository. There are no such lines as what you described ("new DeviceConfiguration...").

**Comment by keijiro** [comment]
I'm closing this issue now. Please feel free to reopen it for further problems.

**Comment by NNskelly** [comment]
The posted snippet appears to be in the Akvfx repo under  Akvfx/Packages/jp.keijiro.akvfx/Runtime/Internal/ThreadedDriver.cs .  So not part of the vj demo per se, but still a relevant question for getting the vj effects working in alternate Kinect configurations.  Can probably re-post in Akvfx.
