### ISSUE TITLE
Mesh from point cloud

### ISSUE THREAD

**Issue by Changliu52** [keijiro/Akvj#2]
Hi @keijiro 

Thank you for sharing the project.

I wonder if you could suggest ways to generate mesh from the point cloud based on this project?

Best Regards,
Chang

**Comment by keijiro** [comment]
This does that: https://github.com/keijiro/Akvj/tree/master/Assets/Surface

**Comment by keijiro** [comment]
I'm closing this issue now. Please feel free to reopen it for further problems.
